/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;
import javax.swing.*;

/** 
    @author Grupo 6 
    Luis Ezequiel Sosa
    Lucas Saidman
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class VistaBorrarCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaBorrarCliente
     */
    public VistaBorrarCliente() {
        initComponents();
        cargarDocumentos();
        
        ((javax.swing.table.DefaultTableModel) tablaClientes.getModel()).setRowCount(0);
        
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
           @Override
           public void keyReleased(java.awt.event.KeyEvent e) {
               String f = txtDni.getText().trim();
               javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
               
               for(String dni : App.FrmMenu.DIRECTORIO.getDocumentos()) {
                   if(f.isEmpty() || dni.contains(f)){
                       modelo.addElement(dni);
                   }
               }
               
               listDni.setModel(modelo);
           }
        });
    }
    
    private void cargarDocumentos(){
        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
        for (String dni : App.FrmMenu.DIRECTORIO.getDocumentos()) {
            modelo.addElement(dni);
        }
        listDni.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorrarCliente = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        spListaDni = new javax.swing.JScrollPane();
        listDni = new javax.swing.JList<>();
        spTablaClientes = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Borrar Cliente");

        lbDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbDni.setText("DNI:");

        listDni.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listDniValueChanged(evt);
            }
        });
        spListaDni.setViewportView(listDni);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Ciudad", "Domicilio", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTablaClientes.setViewportView(tablaClientes);

        btnBorrar.setText("Borrar Cliente/s");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorrarClienteLayout = new javax.swing.GroupLayout(panelBorrarCliente);
        panelBorrarCliente.setLayout(panelBorrarClienteLayout);
        panelBorrarClienteLayout.setHorizontalGroup(
            panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorrarClienteLayout.createSequentialGroup()
                .addGroup(panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBorrarClienteLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(188, 188, 188)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBorrarClienteLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbDni, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spListaDni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(spTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        panelBorrarClienteLayout.setVerticalGroup(
            panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorrarClienteLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addGap(30, 30, 30)
                .addGroup(panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBorrarClienteLayout.createSequentialGroup()
                        .addGroup(panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spListaDni))
                    .addComponent(spTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(panelBorrarClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int row = tablaClientes.getSelectedRow();
        
        if(row == -1){
            JOptionPane.showMessageDialog(this, "Seleccione un registro de la tabla");
            return;
        }
        
        Object telObj = tablaClientes.getValueAt(row, 5);
        Long telefono;
        if (telObj instanceof Long) {
            telefono = (Long) telObj;
        } else {
            telefono = Long.parseLong(telObj.toString());
        }
        
        boolean ok = App.FrmMenu.DIRECTORIO.borrarContacto(telefono);
        JOptionPane.showMessageDialog(this, ok ? "Eliminado" : "No se pudo eliminar el cliente");
        
        if(ok) {
            ((javax.swing.table.DefaultTableModel) tablaClientes.getModel()).removeRow(row);
        }
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void listDniValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listDniValueChanged
        if(evt.getValueIsAdjusting()){
            return;
        }
        
        String dniSelect = listDni.getSelectedValue();
        if(dniSelect == null) {
            return;
        }
        
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();
        model.setRowCount(0);
        
        for(Long tel : App.FrmMenu.DIRECTORIO.getTelefonos()) {
            Controladores.Cliente c = App.FrmMenu.DIRECTORIO.buscarContacto(tel);
            
            if(c != null && dniSelect.equals(c.getDni())){
                model.addRow(new Object[]{c.getDni(), c.getApellido(), c.getNombre(), c.getCiudad(), c.getDomicilio(), tel});
            }
        }
    }//GEN-LAST:event_listDniValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lbDni;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JList<String> listDni;
    private javax.swing.JPanel panelBorrarCliente;
    private javax.swing.JScrollPane spListaDni;
    private javax.swing.JScrollPane spTablaClientes;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtDni;
    // End of variables declaration//GEN-END:variables
}
