/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas;

import java.util.List;

/** 
    @author Grupo 6 
    Luis Ezequiel Sosa
    Lucas Saidman
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class VistaBuscarClienteCiudad extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaBuscarClienteCiudad
     */
    public VistaBuscarClienteCiudad() {
        initComponents();
        cargarCiudades();
        ((javax.swing.table.DefaultTableModel) tablaClientes.getModel()).setRowCount(0);
        
        if(cbCiudades.getItemCount() > 0) {
            cbCiudades.setSelectedIndex(-1);
            cargarTablaPorCiudad();
        }
    }
    
    private void cargarCiudades(){
        cbCiudades.removeAllItems();
        
        for(String c : App.FrmMenu.CIUDADES){
            cbCiudades.addItem(c);
        }
    }
    
    private void cargarTablaPorCiudad(){
        Object select = cbCiudades.getSelectedItem();
        
        if(select == null) {
            ((javax.swing.table.DefaultTableModel) tablaClientes.getModel()).setRowCount(0);
            return;
        }
        
        String ciudad = select.toString();
        
        List<Controladores.Cliente> lista = App.FrmMenu.DIRECTORIO.buscarContactos(ciudad);
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();
        model.setRowCount(0);
        
        for(Controladores.Cliente c : lista){
            for(Long tel : App.FrmMenu.DIRECTORIO.getTelefonos()){
                Controladores.Cliente v = App.FrmMenu.DIRECTORIO.buscarContacto(tel);
                
                if(v != null && v.getDni().equals(c.getDni())) {
                    model.addRow(new Object[]{ c.getDni(), c.getApellido(), c.getNombre(), c.getCiudad(), c.getDomicilio(), tel});
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusquedaClienteCiudad = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbCiudades = new javax.swing.JLabel();
        spTablaClientes = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        cbCiudades = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Buscar Clientes de Directorio por Ciudad");

        lbCiudades.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbCiudades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCiudades.setText("Ciudades:");

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Ciudad", "Domicilio", "Telefono"
            }
        ));
        spTablaClientes.setViewportView(tablaClientes);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        cbCiudades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCiudades.setSelectedIndex(-1);
        cbCiudades.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCiudadesItemStateChanged(evt);
            }
        });
        cbCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCiudadesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBusquedaClienteCiudadLayout = new javax.swing.GroupLayout(panelBusquedaClienteCiudad);
        panelBusquedaClienteCiudad.setLayout(panelBusquedaClienteCiudadLayout);
        panelBusquedaClienteCiudadLayout.setHorizontalGroup(
            panelBusquedaClienteCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBusquedaClienteCiudadLayout.createSequentialGroup()
                .addGroup(panelBusquedaClienteCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaClienteCiudadLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBusquedaClienteCiudadLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelBusquedaClienteCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addComponent(spTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        panelBusquedaClienteCiudadLayout.setVerticalGroup(
            panelBusquedaClienteCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaClienteCiudadLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addGap(30, 30, 30)
                .addGroup(panelBusquedaClienteCiudadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBusquedaClienteCiudadLayout.createSequentialGroup()
                        .addComponent(lbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBusquedaClienteCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBusquedaClienteCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cbCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCiudadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCiudadesActionPerformed

    private void cbCiudadesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCiudadesItemStateChanged
        if (evt.getStateChange() != java.awt.event.ItemEvent.SELECTED) {
            return;
        }

        Object select = cbCiudades.getSelectedItem();
        if (select == null) {
            ((javax.swing.table.DefaultTableModel) tablaClientes.getModel()).setRowCount(0);
            return;
        }
        String ciudad = select.toString();

        java.util.List<Controladores.Cliente> lista = App.FrmMenu.DIRECTORIO.buscarContactos(ciudad);
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();
        model.setRowCount(0);

        // por cada cliente, listar TODOS sus teléfonos
        for (Controladores.Cliente c : lista) {
            for (Long tel : App.FrmMenu.DIRECTORIO.getTelefonos()) {
                Controladores.Cliente v = App.FrmMenu.DIRECTORIO.buscarContacto(tel);
                
                if (v != null && v.getDni().equals(c.getDni())) {
                    model.addRow(new Object[]{ c.getDni(), c.getApellido(), c.getNombre(), c.getCiudad(), c.getDomicilio(), tel });
                }
            }
        }
    }//GEN-LAST:event_cbCiudadesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbCiudades;
    private javax.swing.JLabel lbCiudades;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelBusquedaClienteCiudad;
    private javax.swing.JScrollPane spTablaClientes;
    private javax.swing.JTable tablaClientes;
    // End of variables declaration//GEN-END:variables
}
