package Vistas;

/** 
    @author Grupo 6 
    Luis Ezequiel Sosa
    Lucas Saidman
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class VistaBuscarTelefonoApellido extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaBuscarTelefonoApellido
     */
    public VistaBuscarTelefonoApellido() {
        initComponents();
        cargarApellidos();
        
        ((javax.swing.table.DefaultTableModel) tablaClientes.getModel()).setRowCount(0);
        
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyReleased(java.awt.event.KeyEvent e) {
                String f = txtApellido.getText().trim().toLowerCase();
                javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
                
                for(String ap : App.FrmMenu.DIRECTORIO.getApellidos()) {
                    if(f.isEmpty() || ap.toLowerCase().contains(f)) {
                        modelo.addElement(ap);
                    }
                }
                listApellidos.setModel(modelo);
            }
        });
    }
    
    private void cargarApellidos(){
        javax.swing.DefaultListModel<String> modelo = new javax.swing.DefaultListModel<>();
        
        for(String ap : App.FrmMenu.DIRECTORIO.getApellidos()){
            modelo.addElement(ap);
        }
        
        listApellidos.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBusquedaTelefonoApellido = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        spListaApellidos = new javax.swing.JScrollPane();
        listApellidos = new javax.swing.JList<>();
        spTablaClientes = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Buscar Teléfono por Apellido");

        lbApellido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbApellido.setText("Apellido:");

        listApellidos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listApellidosValueChanged(evt);
            }
        });
        spListaApellidos.setViewportView(listApellidos);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombre", "Ciudad", "Domicilio", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        spTablaClientes.setViewportView(tablaClientes);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBusquedaTelefonoApellidoLayout = new javax.swing.GroupLayout(panelBusquedaTelefonoApellido);
        panelBusquedaTelefonoApellido.setLayout(panelBusquedaTelefonoApellidoLayout);
        panelBusquedaTelefonoApellidoLayout.setHorizontalGroup(
            panelBusquedaTelefonoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
            .addGroup(panelBusquedaTelefonoApellidoLayout.createSequentialGroup()
                .addGroup(panelBusquedaTelefonoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelBusquedaTelefonoApellidoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBusquedaTelefonoApellidoLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelBusquedaTelefonoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(spListaApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(spTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(0, 34, Short.MAX_VALUE))
        );
        panelBusquedaTelefonoApellidoLayout.setVerticalGroup(
            panelBusquedaTelefonoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaTelefonoApellidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbTitulo)
                .addGap(30, 30, 30)
                .addGroup(panelBusquedaTelefonoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelBusquedaTelefonoApellidoLayout.createSequentialGroup()
                        .addGroup(panelBusquedaTelefonoApellidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spListaApellidos))
                    .addComponent(spTablaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBusquedaTelefonoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBusquedaTelefonoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void listApellidosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listApellidosValueChanged
        if (evt.getValueIsAdjusting()) {
            return;
        }
        
        String apellido = listApellidos.getSelectedValue();
        
        if (apellido == null || apellido.trim().isEmpty()) {
            return;
        }

        java.util.Set<Long> telefonos = App.FrmMenu.DIRECTORIO.buscarTelefono(apellido);
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();
        model.setRowCount(0);

        for (Long tel : telefonos) {
            Controladores.Cliente c = App.FrmMenu.DIRECTORIO.buscarContacto(tel);
            if (c != null) {
                model.addRow(new Object[]{ c.getDni(), c.getApellido(), c.getNombre(), c.getCiudad(), c.getDomicilio(), tel });
            }
        }
    }//GEN-LAST:event_listApellidosValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JList<String> listApellidos;
    private javax.swing.JPanel panelBusquedaTelefonoApellido;
    private javax.swing.JScrollPane spListaApellidos;
    private javax.swing.JScrollPane spTablaClientes;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApellido;
    // End of variables declaration//GEN-END:variables
}
