/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

/** 
    @author Grupo 6 
    Luis Ezequiel Sosa
    Lucas Saidman
    Gimenez Diego Ruben
    Carlos German Mecias Giacomelli
    Tomas Migliozzi Badani
    Luca Rodrigaño
    Ignacio Rodriguez
**/

public class FrmMenu extends javax.swing.JFrame {
    
    public static final Controladores.DirectorioTelefonico DIRECTORIO = new Controladores.DirectorioTelefonico();
    public static final java.util.TreeSet<String> CIUDADES = new java.util.TreeSet<>();
    
    private Vistas.VistaAgregarCiudad vistaAgregarCiudad;
    private Vistas.VistaAgregarCliente vistaAgregarCliente;
    private Vistas.VistaBorrarCliente vistaBorrarCliente;
    private Vistas.VistaBuscarCliente vistaBuscarCliente;
    private Vistas.VistaBuscarClienteCiudad vistaBuscarClienteCiudad;
    private Vistas.VistaBuscarTelefonoApellido vistaBuscarTelefonoApellido;

    /**
     * Creates new form JFrame
     */
    public FrmMenu() {
        initComponents();
        CIUDADES.add("San Luis");
        CIUDADES.add("Villa Mercedes");
        CIUDADES.add("Merlo");
        CIUDADES.add("Cordoba");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        itemAgregarCliente = new javax.swing.JMenuItem();
        itemBuscarCliente = new javax.swing.JMenuItem();
        itemBorrarCliente = new javax.swing.JMenuItem();
        menuDirectorio = new javax.swing.JMenu();
        itemBuscarClienteCiudad = new javax.swing.JMenuItem();
        itemBuscarTelefonoApellido = new javax.swing.JMenuItem();
        menuCiudades = new javax.swing.JMenu();
        itemAgregarCiudad = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 565, Short.MAX_VALUE)
        );

        menuClientes.setText("Clientes");

        itemAgregarCliente.setText("Agregar Cliente");
        itemAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(itemAgregarCliente);

        itemBuscarCliente.setText("Buscar Cliente");
        itemBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(itemBuscarCliente);

        itemBorrarCliente.setText("Borrar Cliente");
        itemBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBorrarClienteActionPerformed(evt);
            }
        });
        menuClientes.add(itemBorrarCliente);

        menuBar.add(menuClientes);

        menuDirectorio.setText("Directorio");

        itemBuscarClienteCiudad.setText("Buscar Clientes por Ciudad");
        itemBuscarClienteCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarClienteCiudadActionPerformed(evt);
            }
        });
        menuDirectorio.add(itemBuscarClienteCiudad);

        itemBuscarTelefonoApellido.setText("Buscar Teléfono por Apellido");
        itemBuscarTelefonoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBuscarTelefonoApellidoActionPerformed(evt);
            }
        });
        menuDirectorio.add(itemBuscarTelefonoApellido);

        menuBar.add(menuDirectorio);

        menuCiudades.setText("Ciudades");

        itemAgregarCiudad.setText("Agregar Ciudad");
        itemAgregarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarCiudadActionPerformed(evt);
            }
        });
        menuCiudades.add(itemAgregarCiudad);

        menuBar.add(menuCiudades);

        menuSalir.setText("Salir");

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuSalir.add(itemSalir);

        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itemAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarClienteActionPerformed
        if(vistaAgregarCliente == null || vistaAgregarCliente.isClosed()){
            vistaAgregarCliente = new Vistas.VistaAgregarCliente();
            Escritorio.add(vistaAgregarCliente);
            vistaAgregarCliente.setVisible(true);
        }
    }//GEN-LAST:event_itemAgregarClienteActionPerformed

    private void itemBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarClienteActionPerformed
        if(vistaBuscarCliente == null || vistaBuscarCliente.isClosed()){
            vistaBuscarCliente = new Vistas.VistaBuscarCliente();
            Escritorio.add(vistaBuscarCliente);
            vistaBuscarCliente.setVisible(true);
        }
    }//GEN-LAST:event_itemBuscarClienteActionPerformed

    private void itemBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBorrarClienteActionPerformed
        if(vistaBorrarCliente == null || vistaBorrarCliente.isClosed()){
            vistaBorrarCliente = new Vistas.VistaBorrarCliente();
            Escritorio.add(vistaBorrarCliente);
            vistaBorrarCliente.setVisible(true);
        }
    }//GEN-LAST:event_itemBorrarClienteActionPerformed

    private void itemBuscarClienteCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarClienteCiudadActionPerformed
        if(vistaBuscarClienteCiudad == null || vistaBuscarClienteCiudad.isClosed()){
            vistaBuscarClienteCiudad = new Vistas.VistaBuscarClienteCiudad();
            Escritorio.add(vistaBuscarClienteCiudad);
            vistaBuscarClienteCiudad.setVisible(true);
        }
    }//GEN-LAST:event_itemBuscarClienteCiudadActionPerformed

    private void itemBuscarTelefonoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBuscarTelefonoApellidoActionPerformed
        if(vistaBuscarTelefonoApellido == null || vistaBuscarTelefonoApellido.isClosed()){
            vistaBuscarTelefonoApellido = new Vistas.VistaBuscarTelefonoApellido();
            Escritorio.add(vistaBuscarTelefonoApellido);
            vistaBuscarTelefonoApellido.setVisible(true);
        }
    }//GEN-LAST:event_itemBuscarTelefonoApellidoActionPerformed

    private void itemAgregarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarCiudadActionPerformed
        if(vistaAgregarCiudad == null || vistaAgregarCiudad.isClosed()){
            vistaAgregarCiudad = new Vistas.VistaAgregarCiudad();
            Escritorio.add(vistaAgregarCiudad);
            vistaAgregarCiudad.setVisible(true);
        }
    }//GEN-LAST:event_itemAgregarCiudadActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        dispose();
    }//GEN-LAST:event_itemSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem itemAgregarCiudad;
    private javax.swing.JMenuItem itemAgregarCliente;
    private javax.swing.JMenuItem itemBorrarCliente;
    private javax.swing.JMenuItem itemBuscarCliente;
    private javax.swing.JMenuItem itemBuscarClienteCiudad;
    private javax.swing.JMenuItem itemBuscarTelefonoApellido;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuCiudades;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuDirectorio;
    private javax.swing.JMenu menuSalir;
    // End of variables declaration//GEN-END:variables
}
